const styles = {
  container: { maxWidth: '1100px', margin: '0 auto', padding: '1rem' },
  statsBar: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '0.75rem',
    marginBottom: '1.5rem',
  },
  stat: {
    background: '#1a1a2e',
    color: 'white',
    borderRadius: '10px',
    padding: '0.8rem',
    textAlign: 'center',
  },
  statNum: { display: 'block', fontSize: '1.5rem', fontWeight: 'bold' },
  statLabel: { fontSize: '0.8rem', color: '#a0c4ff' },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  addBtn: {
    background: '#457b9d',
    color: 'white',
    border: 'none',
    padding: '0.6rem 1rem',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '0.95rem',
    whiteSpace: 'nowrap',
  },
  formContainer: {
    background: 'white',
    padding: '1rem',
    borderRadius: '12px',
    marginBottom: '1rem',
    boxShadow: '0 2px 12px rgba(0,0,0,0.08)',
  },
  filters: {
    display: 'flex',
    gap: '0.75rem',
    marginBottom: '1rem',
    flexWrap: 'wrap',
  },
  filterInput: {
    padding: '0.6rem',
    borderRadius: '6px',
    border: '1px solid #ccc',
    fontSize: '0.95rem',
    flex: 1,
    minWidth: '140px',
  },
  loading: { textAlign: 'center', padding: '3rem', color: '#888' },
  empty: { textAlign: 'center', padding: '3rem', color: '#888' },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))',
    gap: '1rem',
  },
  card: {
    background: 'white',
    borderRadius: '12px',
    padding: '1.2rem',
    boxShadow: '0 2px 12px rgba(0,0,0,0.08)',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '0.5rem',
  },
  visited: { fontSize: '1.2rem' },
  priority: { fontSize: '0.9rem' },
  destName: { margin: '0 0 0.3rem', fontSize: '1.1rem', color: '#1a1a2e' },
  location: { color: '#666', margin: '0 0 0.3rem', fontSize: '0.85rem' },
  cost: { color: '#457b9d', fontWeight: 'bold', margin: '0 0 0.5rem' },
  notes: { color: '#888', fontSize: '0.8rem', margin: '0 0 1rem' },
  cardActions: { display: 'flex', gap: '0.5rem' },
  viewBtn: {
    flex: 1, background: '#1a1a2e', color: 'white',
    border: 'none', padding: '0.5rem',
    borderRadius: '6px', cursor: 'pointer',
    fontSize: '0.9rem',
  },
  deleteBtn: {
    flex: 1, background: '#e63946', color: 'white',
    border: 'none', padding: '0.5rem',
    borderRadius: '6px', cursor: 'pointer',
    fontSize: '0.9rem',
  },
  pagination: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '1rem',
    marginTop: '1.5rem',
    flexWrap: 'wrap',
  },
  pageBtn: {
    background: '#1a1a2e', color: 'white',
    border: 'none', padding: '0.5rem 1rem',
    borderRadius: '6px', cursor: 'pointer',
  },
};